## For HWK 3, solving linear programming problem

library(lpSolveAPI)
library(ggplot2)

#Read the datasets
eia=read.csv('RHODES_JOSHUA_EIA_2016_data_OPTHW.csv')
eia_sub=data.frame(eia)

fuel_prop=read.csv('fuel_properties.csv')
fuel_prop=data.frame(fuel_prop)

# Selecting the subset
# Capacity greater than 50
eia_sub=eia_sub[eia_sub$Nameplate.Capacity>50,]
# heat rate greater than 0 and less than 20000
eia_sub=eia_sub[eia_sub$heat_rate>0&eia_sub$heat_rate<20000,]
# Removing the NAs
eia_sub=na.omit(eia_sub)
# selecting the fuel types
generator=eia_sub[eia_sub$Energy.Source.1 %in% fuel_prop$energy_name,]

## Merging the two datasets
generator=merge(x=generator,y=fuel_prop,by.x="Energy.Source.1",by.y = "energy_name",all.x = TRUE,sort = FALSE)

# Adding the Cg and Rg to the 
generator$dol_per_MWh<-generator$Elec.Fuel.Consumption.MMBtu*generator$dol_per_mmBtu/generator$Net.Generation.MWh
generator$ton_CO2_per_MWh<-generator$Elec.Fuel.Consumption.MMBtu*generator$kg_CO2_per_mmBtu/generator$Net.Generation.MWh/1000
generator=generator[,-c(17:19)]

# Printing the head of the generator dataframe
head(generator)

#define the right hand side of the constraints
demand <- 550000
emissions_cap <- 350000

## No.of decision variables is same as number of rows
dv=nrow(generator)

#create an LP model with 2 constraints and dv decision variables
lpmodel<-make.lp(2,dv)

# Constraint that variable is limited by generator capacity
set.bounds(lpmodel, upper = generator$Nameplate.Capacity)

#set constraints
set.row(lpmodel, 1, c(rep(1,dv)))
set.row(lpmodel, 2, generator$ton_CO2_per_MWh)
set.rhs(lpmodel, c(demand, emissions_cap))
set.constr.type(lpmodel, c(">=", "<="))


#set objective coefficients
set.objfn(lpmodel, generator$dol_per_MWh)

#set objective direction
lp.control(lpmodel,sense='min')

# Writing the model in files
write.lp(lpmodel,'VARANASI_HW3.lp',type='lp')

#solve the model, if this return 0 an optimal solution is found
solve(lpmodel)

#this returns the proposed solution
obj_value=get.objective(lpmodel) #value of the objective 

# Printing the objective values
obj_value


# Printing the objective values divided by demand constraint
obj_value/demand 

generator$Energy_Generated=get.variables(lpmodel) #value of the variables for achieving the objective 
constraint_value=get.constraints(lpmodel) #value of the constraint equations. If get.constraints = the right hand side of the constraint equation, then that constraint is "binding" and the solution could be better if we could improve that constraint. For example, the money constraint in the solution is $13,781.25 which is less than the $15,000 of money the farmer starts with. So giving the farmer more money up front would not enable them to make more profit. However, the storage constraint is 4,000 which is equal to the farmer's 4000 bushel storage capacity. So giving the farmer more storage capacity might enable them to increase profit.
# Printing the constraint value
constraint_value

# Table containing energy generated by each fuel type
results_table = aggregate(generator$Energy_Generated, by=list(generator$Energy.Source.1), FUN="sum")

# Printing out the Table showing how much energy was generated by each fuel type 
results_table

### Part 2 ###

#results_df = data.frame()

#results = c()
results = c()
obj_val_list = c()


E_list = seq(350000,230000, -10000)
for (E in E_list) {
  lpmodel <- make.lp(2, dv)
  # Constraint that 
  set.bounds(lpmodel, upper = generator$Nameplate.Capacity)
  
  #set constraints
  
  set.row(lpmodel, 1, c(rep(1,dv)))
  set.row(lpmodel, 2, generator$ton_CO2_per_MWh)
  set.rhs(lpmodel, c(demand, E))
  set.constr.type(lpmodel, c(">=", "<="))
  
  
  #set objective coefficients
  set.objfn(lpmodel, generator$dol_per_MWh)
  
  #set objective direction
  lp.control(lpmodel,sense='min')
  
  #solve the model, if this returns 0 an optimal solution is found
  solve(lpmodel)
  obj_value = get.objective(lpmodel) #value of the objective 
  obj_value/demand
  
  get.constraints(lpmodel) 
  generator$Energy_Generated = get.variables(lpmodel)
  
  results_table2 = aggregate(generator$Energy_Generated, by=list(generator$Energy.Source.1), FUN="sum")
  
  Energy_Generated = get.variables(lpmodel)
  #results = cbind(E, results, c(obj_value, Energy_Generated))
  results = cbind(results, as.numeric(results_table2$x))
  obj_val_list = c(obj_val_list, obj_value/demand)
}  

results = as.data.frame(cbind(as.character(results_table2$Group.1), results))
results$diff = as.numeric(as.character(results$V14)) - as.numeric(as.character(results$V2))


# Printing the plots
ggplot(results, aes(x=V1, y=diff) )+
  geom_bar(stat="identity", color="black", fill="green")+labs(x='Fuel Type',y='Changes in Dispatch from High to Low Emissions cap')

line_results=data.frame(emissions=E_list,dispatch_cost=obj_val_list)


ggplot(line_results, aes(x = emissions, y = dispatch_cost))+labs(x='Emissions Cap(Tons)',y='Dispatch Cost ($MWh)')+
  geom_line(color="red")+ylim(0,30)



